name: navigation
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^8.1.0
  home:
    path: ../features/home
  detailed_view:
    path: ../features/detailed_view


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9



flutter:
