name: pokemon_application
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.2
  cupertino_icons: ^1.0.2
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  data:
    path: ./data
  domain:
    path: ./domain
  home:
    path: ./features/home


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
