name: core
description: A new Flutter project.
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.4.0
  equatable: ^2.0.2
  auto_route: ^7.8.0
  navigation:
    path: ../navigation
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
